# $\color{ForestGreen}{\text{Eigenvalue Problems in Linear Algebra}}$

## $\color{ForestGreen}{\text{Matrix Multiplication}}$

In [1]:
# Import 'numpy' library

import numpy as np

A = np.array([[1, 3, 4], [2, -1, -2]])      # Define matrix 'A' as a numpy array
B = np.array([[-2, -1, 4, 5], [-3, 4, -1, 5], [6, -4, 7, -2]])     # Define matrix 'B' as a numpy array

np.matmul(A, B)       # Calculate matrix 'AB' through 'matmul' 

array([[ 13,  -5,  29,  12],
       [-13,   2,  -5,   9]])

In [2]:
# Import 'sympy' library

from sympy import *

mat_A = Matrix(A)    # Define matrix 'A'
mat_B = Matrix(B)    # Define matrix 'B'

display(mat_A, mat_B)  # Display matrices 'A' and 'B'

Matrix([
[1,  3,  4],
[2, -1, -2]])

Matrix([
[-2, -1,  4,  5],
[-3,  4, -1,  5],
[ 6, -4,  7, -2]])

In [3]:
mat_AB = mat_A*mat_B   # Matrix multiplication in sympy is done by '*'

display(mat_AB)        # Display the result of multiplication

Matrix([
[ 13, -5, 29, 12],
[-13,  2, -5,  9]])

## $\color{ForestGreen}{\text{Determinants and Inverse Matrix}}$

In [4]:
A = np.array([[3, 2, -1, 4], [-2, 3, 5, -3], [1, 2, -3, 5], [4, -3, 1, -2]])  # Define matrix 'A' as a numpy array

np.linalg.det(A)  # To calculate determinant, you need to call the 'linalg' module of numpy

12.000000000000048

In [5]:
mat_A = Matrix(A)   # Define matrix 'A'

mat_A.det()         # calculate the determinant simply by joining '.det()' to the name of matrix

12

In [6]:
B = np.array([[1, -2, 2, -1], [2, -2, 2, 1], [2, -1, 2, -1], [1, -1, 1, 2]]) # Define matrix 'B' as a numpy array

np.linalg.det(B)    # Calculate determinant of 'B'

2.9999999999999996

In [7]:
np.linalg.inv(B)    # Calculate inverse of 'B' through '.inv(matrix name)'

array([[-1.        ,  1.66666667,  0.        , -1.33333333],
       [-0.        , -1.66666667,  1.        ,  1.33333333],
       [ 1.        , -2.66666667,  1.        ,  2.33333333],
       [ 0.        , -0.33333333,  0.        ,  0.66666667]])

In [8]:
mat_B = Matrix(B)  # Define matrix 'B'

mat_B.det()        # Calculate determinant of 'B'

3

In [9]:
Binv = mat_B.inv()   # Calculate inverse of 'B' through 'matrix_name.inv()'

display(Binv)        # Display inverse of 'B'

Matrix([
[-1,  5/3, 0, -4/3],
[ 0, -5/3, 1,  4/3],
[ 1, -8/3, 1,  7/3],
[ 0, -1/3, 0,  2/3]])

In [10]:
display(B*Binv, Binv*B)  # Multiply 'B' with 'B^{-1}' in both orders and display the result

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

## $\color{ForestGreen}{\text{Eigenvalues and Eigenvectors}}$

In [11]:
A = np.array([[1, 0, 2], [-2, 2, 2], [1, 0, 3]])   # Define matrix 'A'

# 'linalg.eig(matrix_name)' calculates both eigenvalues and eigenvectors: 

print('Eigenvalues of A:', np.linalg.eig(A)[0], '\n')    # 'linalg.eig(A)[0]' gives eigenvalues
print('Eigenvectors of A:\n', np.linalg.eig(A)[1])       # 'linalg.eig(A)[1]' gives eigenvectors 

Eigenvalues of A: [2.         0.26794919 3.73205081] 

Eigenvectors of A:
 [[ 0.         -0.52544259 -0.57310042]
 [ 1.         -0.82880701 -0.24222074]
 [ 0.          0.19232534 -0.78286973]]


In [12]:
# You can also use '.eigenvals(matrix_name)' in numpy to calculate eigenvalues

np.linalg.eigvals(A)

array([2.        , 0.26794919, 3.73205081])

In [13]:
# Through 'sympy'

mat_A = Matrix(A)   # Define matrix A

mat_A.eigenvals()   # Calculating eigenvalues through 'sympy'

{2: 1, 2 - sqrt(3): 1, sqrt(3) + 2: 1}

In [14]:
mat_A.eigenvects()  # Calculating eigenvalues and eigenvectors simultaneously in 'sympy' 

[(2,
  1,
  [Matrix([
   [0],
   [1],
   [0]])]),
 (2 - sqrt(3),
  1,
  [Matrix([
   [               -2/(-1 + sqrt(3))],
   [-(-2*sqrt(3) - 2)/(-3 + sqrt(3))],
   [                               1]])]),
 (sqrt(3) + 2,
  1,
  [Matrix([
   [             -2/(-sqrt(3) - 1)],
   [-(2 - 2*sqrt(3))/(sqrt(3) + 3)],
   [                             1]])])]